//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManagement {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class DataManagement : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataManagement defaultInstance = ((DataManagement)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataManagement())));
        
        public static DataManagement Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\AdditionalFiles\\Sales-Reports.zip")]
        public string SalesReportsZipFile
        {
            get
            {
                return ((string)(this["SalesReportsZipFile"]));
            }
            set
            {
                this["SalesReportsZipFile"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\AdditionalFiles\\Aggregated-Sales-Report.pdf")]
        public string PdfSalesReportLocation
        {
            get
            {
                return ((string)(this["PdfSalesReportLocation"]));
            }
            set
            {
                this["PdfSalesReportLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\AdditionalFiles\\Verdana.ttf")]
        public string VerdanaFontLocation
        {
            get
            {
                return ((string)(this["VerdanaFontLocation"]));
            }
            set
            {
                this["VerdanaFontLocation"] = value;
            }
        }
    }
}
